//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int IdProducto { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> idColor { get; set; }
        public Nullable<int> idTalle { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Talle Talle { get; set; }
    }
}
